UPDATE [dbo].[Countries] SET [name] = 'Afghanistan' WHERE name = 'Afghanistan'
UPDATE [dbo].[Countries] SET [name] = 'Aland-eilanden' WHERE name = 'Åland Islands'
UPDATE [dbo].[Countries] SET [name] = 'Albanië' WHERE name = 'Albania'
UPDATE [dbo].[Countries] SET [name] = 'Algerije' WHERE name = 'Algeria'
UPDATE [dbo].[Countries] SET [name] = 'Amerikaans Samoa' WHERE name = 'American Samoa'
UPDATE [dbo].[Countries] SET [name] = 'Andorra' WHERE name = 'Andorra'
UPDATE [dbo].[Countries] SET [name] = 'Angola' WHERE name = 'Angola'
UPDATE [dbo].[Countries] SET [name] = 'Anguilla' WHERE name = 'Anguilla'
UPDATE [dbo].[Countries] SET [name] = 'Antarctica' WHERE name = 'Antarctica'
UPDATE [dbo].[Countries] SET [name] = 'Antigua en Barbuda' WHERE name = 'Antigua and Barbuda'
UPDATE [dbo].[Countries] SET [name] = 'Argentinië' WHERE name = 'Argentina'
UPDATE [dbo].[Countries] SET [name] = 'Armenië' WHERE name = 'Armenia'
UPDATE [dbo].[Countries] SET [name] = 'Aruba' WHERE name = 'Aruba'
UPDATE [dbo].[Countries] SET [name] = 'Australië' WHERE name = 'Australia'
UPDATE [dbo].[Countries] SET [name] = 'Oostenrijk' WHERE name = 'Austria'
UPDATE [dbo].[Countries] SET [name] = 'Azerbeidzjan' WHERE name = 'Azerbaijan'
UPDATE [dbo].[Countries] SET [name] = 'Bahamas' WHERE name = 'Bahamas'
UPDATE [dbo].[Countries] SET [name] = 'Bahrein' WHERE name = 'Bahrain'
UPDATE [dbo].[Countries] SET [name] = 'Bangladesh' WHERE name = 'Bangladesh'
UPDATE [dbo].[Countries] SET [name] = 'Barbados' WHERE name = 'Barbados'
UPDATE [dbo].[Countries] SET [name] = 'Wit-Rusland' WHERE name = 'Belarus'
UPDATE [dbo].[Countries] SET [name] = 'België' WHERE name = 'Belgium'
UPDATE [dbo].[Countries] SET [name] = 'Belize' WHERE name = 'Belize'
UPDATE [dbo].[Countries] SET [name] = 'Benin' WHERE name = 'Benin'
UPDATE [dbo].[Countries] SET [name] = 'Bermuda' WHERE name = 'Bermuda'
UPDATE [dbo].[Countries] SET [name] = 'Bhutan' WHERE name = 'Bhutan'
UPDATE [dbo].[Countries] SET [name] = 'Bolivia' WHERE name = 'Bolivia'
UPDATE [dbo].[Countries] SET [name] = 'Bonaire, Sint Eustatius en Saba' WHERE name = 'Bonaire, Sint Eustatius and Saba'
UPDATE [dbo].[Countries] SET [name] = 'Bosnië-Herzegovina' WHERE name = 'Bosnia and Herzegovina'
UPDATE [dbo].[Countries] SET [name] = 'Botswana' WHERE name = 'Botswana'
UPDATE [dbo].[Countries] SET [name] = 'Bouvet Island' WHERE name = 'Bouvet Island'
UPDATE [dbo].[Countries] SET [name] = 'Brazilië' WHERE name = 'Brazil'
UPDATE [dbo].[Countries] SET [name] = 'Brits-Indisch oceaan gebied' WHERE name = 'British Indian Ocean Territory'
UPDATE [dbo].[Countries] SET [name] = 'Britse Maagdeneilanden' WHERE name = 'British Virgin Islands'
UPDATE [dbo].[Countries] SET [name] = 'Brunei' WHERE name = 'Brunei'
UPDATE [dbo].[Countries] SET [name] = 'Bulgarije' WHERE name = 'Bulgaria'
UPDATE [dbo].[Countries] SET [name] = 'Burkina Faso' WHERE name = 'Burkina Faso'
UPDATE [dbo].[Countries] SET [name] = 'Burundi' WHERE name = 'Burundi'
UPDATE [dbo].[Countries] SET [name] = 'Cabo Verde' WHERE name = 'Cabo Verde'
UPDATE [dbo].[Countries] SET [name] = 'Cambodja' WHERE name = 'Cambodia'
UPDATE [dbo].[Countries] SET [name] = 'Kameroen' WHERE name = 'Cameroon'
UPDATE [dbo].[Countries] SET [name] = 'Canada' WHERE name = 'Canada'
UPDATE [dbo].[Countries] SET [name] = 'AUTO' WHERE name = 'CAR'
UPDATE [dbo].[Countries] SET [name] = 'Kaaiman Eilanden' WHERE name = 'Cayman Islands'
UPDATE [dbo].[Countries] SET [name] = 'Tsjaad' WHERE name = 'Chad'
UPDATE [dbo].[Countries] SET [name] = 'Kanaal eilanden' WHERE name = 'Channel Islands'
UPDATE [dbo].[Countries] SET [name] = 'Chili' WHERE name = 'Chile'
UPDATE [dbo].[Countries] SET [name] = 'China' WHERE name = 'China'
UPDATE [dbo].[Countries] SET [name] = 'Kersteiland' WHERE name = 'Christmas Island'
UPDATE [dbo].[Countries] SET [name] = 'Cocos (Keeling) eilanden' WHERE name = 'Cocos (Keeling) Islands'
UPDATE [dbo].[Countries] SET [name] = 'Colombia' WHERE name = 'Colombia'
UPDATE [dbo].[Countries] SET [name] = 'Comoren' WHERE name = 'Comoros'
UPDATE [dbo].[Countries] SET [name] = 'Congo' WHERE name = 'Congo'
UPDATE [dbo].[Countries] SET [name] = 'Cookeilanden' WHERE name = 'Cook Islands'
UPDATE [dbo].[Countries] SET [name] = 'Costa Rica' WHERE name = 'Costa Rica'
UPDATE [dbo].[Countries] SET [name] = 'Kroatië' WHERE name = 'Croatia'
UPDATE [dbo].[Countries] SET [name] = 'Cuba' WHERE name = 'Cuba'
UPDATE [dbo].[Countries] SET [name] = 'Curacao' WHERE name = 'Curaçao'
UPDATE [dbo].[Countries] SET [name] = 'Cyprus' WHERE name = 'Cyprus'
UPDATE [dbo].[Countries] SET [name] = 'Tsjechië' WHERE name = 'Czech Republic'
UPDATE [dbo].[Countries] SET [name] = 'Denemarken' WHERE name = 'Denmark'
UPDATE [dbo].[Countries] SET [name] = 'Djibouti' WHERE name = 'Djibouti'
UPDATE [dbo].[Countries] SET [name] = 'Dominica' WHERE name = 'Dominica'
UPDATE [dbo].[Countries] SET [name] = 'Dominicaanse Republiek' WHERE name = 'Dominican Republic'
UPDATE [dbo].[Countries] SET [name] = 'DRC' WHERE name = 'DRC'
UPDATE [dbo].[Countries] SET [name] = 'Ecuador' WHERE name = 'Ecuador'
UPDATE [dbo].[Countries] SET [name] = 'Egypte' WHERE name = 'Egypt'
UPDATE [dbo].[Countries] SET [name] = 'El Salvador' WHERE name = 'El Salvador'
UPDATE [dbo].[Countries] SET [name] = 'Equatoriaal-Guinea' WHERE name = 'Equatorial Guinea'
UPDATE [dbo].[Countries] SET [name] = 'Eritrea' WHERE name = 'Eritrea'
UPDATE [dbo].[Countries] SET [name] = 'Estland' WHERE name = 'Estonia'
UPDATE [dbo].[Countries] SET [name] = 'Eswatini' WHERE name = 'Eswatini'
UPDATE [dbo].[Countries] SET [name] = 'Ethiopië' WHERE name = 'Ethiopia'
UPDATE [dbo].[Countries] SET [name] = 'Faeröer' WHERE name = 'Faeroe Islands'
UPDATE [dbo].[Countries] SET [name] = 'Falkland Eilanden' WHERE name = 'Falkland Islands'
UPDATE [dbo].[Countries] SET [name] = 'Fiji' WHERE name = 'Fiji'
UPDATE [dbo].[Countries] SET [name] = 'Finland' WHERE name = 'Finland'
UPDATE [dbo].[Countries] SET [name] = 'Frankrijk' WHERE name = 'France'
UPDATE [dbo].[Countries] SET [name] = 'Frans-Guyana' WHERE name = 'French Guiana'
UPDATE [dbo].[Countries] SET [name] = 'Frans-Polynesië' WHERE name = 'French Polynesia'
UPDATE [dbo].[Countries] SET [name] = 'Franse zuidelijke gebieden' WHERE name = 'French Southern Territories'
UPDATE [dbo].[Countries] SET [name] = 'Gabon' WHERE name = 'Gabon'
UPDATE [dbo].[Countries] SET [name] = 'Gambia' WHERE name = 'Gambia'
UPDATE [dbo].[Countries] SET [name] = 'Georgië' WHERE name = 'Georgia'
UPDATE [dbo].[Countries] SET [name] = 'Duitsland' WHERE name = 'Germany'
UPDATE [dbo].[Countries] SET [name] = 'Ghana' WHERE name = 'Ghana'
UPDATE [dbo].[Countries] SET [name] = 'Gibraltar' WHERE name = 'Gibraltar'
UPDATE [dbo].[Countries] SET [name] = 'Griekenland' WHERE name = 'Greece'
UPDATE [dbo].[Countries] SET [name] = 'Groenland' WHERE name = 'Greenland'
UPDATE [dbo].[Countries] SET [name] = 'Grenada' WHERE name = 'Grenada'
UPDATE [dbo].[Countries] SET [name] = 'Guadeloupe' WHERE name = 'Guadeloupe'
UPDATE [dbo].[Countries] SET [name] = 'Guam' WHERE name = 'Guam'
UPDATE [dbo].[Countries] SET [name] = 'Guatemala' WHERE name = 'Guatemala'
UPDATE [dbo].[Countries] SET [name] = 'Guernsey' WHERE name = 'Guernsey'
UPDATE [dbo].[Countries] SET [name] = 'Guinea' WHERE name = 'Guinea'
UPDATE [dbo].[Countries] SET [name] = 'Guinee-Bissau' WHERE name = 'Guinea-Bissau'
UPDATE [dbo].[Countries] SET [name] = 'Guyana' WHERE name = 'Guyana'
UPDATE [dbo].[Countries] SET [name] = 'Haïti' WHERE name = 'Haiti'
UPDATE [dbo].[Countries] SET [name] = 'Heard Island en Mcdonald Islands' WHERE name = 'Heard Island and Mcdonald Islands'
UPDATE [dbo].[Countries] SET [name] = 'Honduras' WHERE name = 'Honduras'
UPDATE [dbo].[Countries] SET [name] = 'Hong Kong' WHERE name = 'Hong Kong'
UPDATE [dbo].[Countries] SET [name] = 'Hongarije' WHERE name = 'Hungary'
UPDATE [dbo].[Countries] SET [name] = 'IJsland' WHERE name = 'Iceland'
UPDATE [dbo].[Countries] SET [name] = 'India' WHERE name = 'India'
UPDATE [dbo].[Countries] SET [name] = 'Indonesië' WHERE name = 'Indonesia'
UPDATE [dbo].[Countries] SET [name] = 'Ik rende' WHERE name = 'Iran'
UPDATE [dbo].[Countries] SET [name] = 'Irak' WHERE name = 'Iraq'
UPDATE [dbo].[Countries] SET [name] = 'Ierland' WHERE name = 'Ireland'
UPDATE [dbo].[Countries] SET [name] = 'Isle of Man' WHERE name = 'Isle of Man'
UPDATE [dbo].[Countries] SET [name] = 'Israël' WHERE name = 'Israel'
UPDATE [dbo].[Countries] SET [name] = 'Italië' WHERE name = 'Italy'
UPDATE [dbo].[Countries] SET [name] = 'Ivoorkust' WHERE name = 'Ivory Coast'
UPDATE [dbo].[Countries] SET [name] = 'Jamaica' WHERE name = 'Jamaica'
UPDATE [dbo].[Countries] SET [name] = 'Japan' WHERE name = 'Japan'
UPDATE [dbo].[Countries] SET [name] = 'Jersey' WHERE name = 'Jersey'
UPDATE [dbo].[Countries] SET [name] = 'Jordanië' WHERE name = 'Jordan'
UPDATE [dbo].[Countries] SET [name] = 'Kazachstan' WHERE name = 'Kazakhstan'
UPDATE [dbo].[Countries] SET [name] = 'Kenia' WHERE name = 'Kenya'
UPDATE [dbo].[Countries] SET [name] = 'Kiribati' WHERE name = 'Kiribati'
UPDATE [dbo].[Countries] SET [name] = 'Kosovo * (betwist gebied)' WHERE name = 'Kosovo* (disputed teritory)'
UPDATE [dbo].[Countries] SET [name] = 'Koeweit' WHERE name = 'Kuwait'
UPDATE [dbo].[Countries] SET [name] = 'Kirgizië' WHERE name = 'Kyrgyzstan'
UPDATE [dbo].[Countries] SET [name] = 'Laos' WHERE name = 'Laos'
UPDATE [dbo].[Countries] SET [name] = 'Letland' WHERE name = 'Latvia'
UPDATE [dbo].[Countries] SET [name] = 'Libanon' WHERE name = 'Lebanon'
UPDATE [dbo].[Countries] SET [name] = 'Lesotho' WHERE name = 'Lesotho'
UPDATE [dbo].[Countries] SET [name] = 'Liberia' WHERE name = 'Liberia'
UPDATE [dbo].[Countries] SET [name] = 'Libië' WHERE name = 'Libya'
UPDATE [dbo].[Countries] SET [name] = 'Liechtenstein' WHERE name = 'Liechtenstein'
UPDATE [dbo].[Countries] SET [name] = 'Litouwen' WHERE name = 'Lithuania'
UPDATE [dbo].[Countries] SET [name] = 'Luxemburg' WHERE name = 'Luxembourg'
UPDATE [dbo].[Countries] SET [name] = 'Macao' WHERE name = 'Macao'
UPDATE [dbo].[Countries] SET [name] = 'Madagascar' WHERE name = 'Madagascar'
UPDATE [dbo].[Countries] SET [name] = 'Malawi' WHERE name = 'Malawi'
UPDATE [dbo].[Countries] SET [name] = 'Maleisië' WHERE name = 'Malaysia'
UPDATE [dbo].[Countries] SET [name] = 'Maldiven' WHERE name = 'Maldives'
UPDATE [dbo].[Countries] SET [name] = 'Mali' WHERE name = 'Mali'
UPDATE [dbo].[Countries] SET [name] = 'Malta' WHERE name = 'Malta'
UPDATE [dbo].[Countries] SET [name] = 'Marshall eilanden' WHERE name = 'Marshall Islands'
UPDATE [dbo].[Countries] SET [name] = 'Martinique' WHERE name = 'Martinique'
UPDATE [dbo].[Countries] SET [name] = 'Mauritanië' WHERE name = 'Mauritania'
UPDATE [dbo].[Countries] SET [name] = 'Mauritius' WHERE name = 'Mauritius'
UPDATE [dbo].[Countries] SET [name] = 'Mayotte' WHERE name = 'Mayotte'
UPDATE [dbo].[Countries] SET [name] = 'Mexico' WHERE name = 'Mexico'
UPDATE [dbo].[Countries] SET [name] = 'Micronesië' WHERE name = 'Micronesia'
UPDATE [dbo].[Countries] SET [name] = 'Moldavië' WHERE name = 'Moldova'
UPDATE [dbo].[Countries] SET [name] = 'Monaco' WHERE name = 'Monaco'
UPDATE [dbo].[Countries] SET [name] = 'Mongolië' WHERE name = 'Mongolia'
UPDATE [dbo].[Countries] SET [name] = 'Montenegro' WHERE name = 'Montenegro'
UPDATE [dbo].[Countries] SET [name] = 'Montserrat' WHERE name = 'Montserrat'
UPDATE [dbo].[Countries] SET [name] = 'Marokko' WHERE name = 'Morocco'
UPDATE [dbo].[Countries] SET [name] = 'Mozambique' WHERE name = 'Mozambique'
UPDATE [dbo].[Countries] SET [name] = 'Myanmar' WHERE name = 'Myanmar'
UPDATE [dbo].[Countries] SET [name] = 'Namibië' WHERE name = 'Namibia'
UPDATE [dbo].[Countries] SET [name] = 'Nauru' WHERE name = 'Nauru'
UPDATE [dbo].[Countries] SET [name] = 'Nepal' WHERE name = 'Nepal'
UPDATE [dbo].[Countries] SET [name] = 'Nederland' WHERE name = 'Netherlands'
UPDATE [dbo].[Countries] SET [name] = 'Nieuw-Caledonië' WHERE name = 'New Caledonia'
UPDATE [dbo].[Countries] SET [name] = 'Nieuw-Zeeland' WHERE name = 'New Zealand'
UPDATE [dbo].[Countries] SET [name] = 'Nicaragua' WHERE name = 'Nicaragua'
UPDATE [dbo].[Countries] SET [name] = 'Niger' WHERE name = 'Niger'
UPDATE [dbo].[Countries] SET [name] = 'Nigeria' WHERE name = 'Nigeria'
UPDATE [dbo].[Countries] SET [name] = 'Niue' WHERE name = 'Niue'
UPDATE [dbo].[Countries] SET [name] = 'Norfolkeiland' WHERE name = 'Norfolk Island'
UPDATE [dbo].[Countries] SET [name] = 'Noord Korea' WHERE name = 'North Korea'
UPDATE [dbo].[Countries] SET [name] = 'Noord-Macedonië' WHERE name = 'North Macedonia'
UPDATE [dbo].[Countries] SET [name] = 'noordelijke Mariana eilanden' WHERE name = 'Northern Mariana Islands'
UPDATE [dbo].[Countries] SET [name] = 'Noorwegen' WHERE name = 'Norway'
UPDATE [dbo].[Countries] SET [name] = 'Oman' WHERE name = 'Oman'
UPDATE [dbo].[Countries] SET [name] = 'Pakistan' WHERE name = 'Pakistan'
UPDATE [dbo].[Countries] SET [name] = 'Palau' WHERE name = 'Palau'
UPDATE [dbo].[Countries] SET [name] = 'Palestina' WHERE name = 'Palestine'
UPDATE [dbo].[Countries] SET [name] = 'Panama' WHERE name = 'Panama'
UPDATE [dbo].[Countries] SET [name] = 'Papoea-Nieuw-Guinea' WHERE name = 'Papua New Guinea'
UPDATE [dbo].[Countries] SET [name] = 'Paraguay' WHERE name = 'Paraguay'
UPDATE [dbo].[Countries] SET [name] = 'Peru' WHERE name = 'Peru'
UPDATE [dbo].[Countries] SET [name] = 'Filippijnen' WHERE name = 'Philippines'
UPDATE [dbo].[Countries] SET [name] = 'Pitcairn' WHERE name = 'Pitcairn'
UPDATE [dbo].[Countries] SET [name] = 'Polen' WHERE name = 'Poland'
UPDATE [dbo].[Countries] SET [name] = 'Portugal' WHERE name = 'Portugal'
UPDATE [dbo].[Countries] SET [name] = 'Puerto Rico' WHERE name = 'Puerto Rico'
UPDATE [dbo].[Countries] SET [name] = 'Qatar' WHERE name = 'Qatar'
UPDATE [dbo].[Countries] SET [name] = 'Bijeenkomst' WHERE name = 'Reunion'
UPDATE [dbo].[Countries] SET [name] = 'Roemenië' WHERE name = 'Romania'
UPDATE [dbo].[Countries] SET [name] = 'Rusland' WHERE name = 'Russia'
UPDATE [dbo].[Countries] SET [name] = 'Rwanda' WHERE name = 'Rwanda'
UPDATE [dbo].[Countries] SET [name] = 'Sint-Bartholomeus' WHERE name = 'Saint Barthélemy'
UPDATE [dbo].[Countries] SET [name] = 'Sint-Helena, Ascension en Tristan da Cunha' WHERE name = 'Saint Helena, Ascension and Tristan da Cunha'
UPDATE [dbo].[Countries] SET [name] = 'Saint Kitts en Nevis' WHERE name = 'Saint Kitts and Nevis'
UPDATE [dbo].[Countries] SET [name] = 'Saint Lucia' WHERE name = 'Saint Lucia'
UPDATE [dbo].[Countries] SET [name] = 'Sint-Maarten' WHERE name = 'Saint Martin'
UPDATE [dbo].[Countries] SET [name] = 'Saint Pierre en Miquelon' WHERE name = 'Saint Pierre and Miquelon'
UPDATE [dbo].[Countries] SET [name] = 'Samoa' WHERE name = 'Samoa'
UPDATE [dbo].[Countries] SET [name] = 'San Marino' WHERE name = 'San Marino'
UPDATE [dbo].[Countries] SET [name] = 'Sao Tome en Principe' WHERE name = 'Sao Tome and Principe'
UPDATE [dbo].[Countries] SET [name] = 'Saoedi-Arabië' WHERE name = 'Saudi Arabia'
UPDATE [dbo].[Countries] SET [name] = 'Senegal' WHERE name = 'Senegal'
UPDATE [dbo].[Countries] SET [name] = 'Servië' WHERE name = 'Serbia'
UPDATE [dbo].[Countries] SET [name] = 'Seychellen' WHERE name = 'Seychelles'
UPDATE [dbo].[Countries] SET [name] = 'Sierra Leone' WHERE name = 'Sierra Leone'
UPDATE [dbo].[Countries] SET [name] = 'Singapore' WHERE name = 'Singapore'
UPDATE [dbo].[Countries] SET [name] = 'Sint Maarten' WHERE name = 'Sint Maarten'
UPDATE [dbo].[Countries] SET [name] = 'Slowakije' WHERE name = 'Slovakia'
UPDATE [dbo].[Countries] SET [name] = 'Slovenië' WHERE name = 'Slovenia'
UPDATE [dbo].[Countries] SET [name] = 'Solomon eilanden' WHERE name = 'Solomon Islands'
UPDATE [dbo].[Countries] SET [name] = 'Somalië' WHERE name = 'Somalia'
UPDATE [dbo].[Countries] SET [name] = 'Zuid-Afrika' WHERE name = 'South Africa'
UPDATE [dbo].[Countries] SET [name] = 'Zuid-Georgië en de Zuidelijke Sandwicheilanden' WHERE name = 'South Georgia and the South Sandwich Islands'
UPDATE [dbo].[Countries] SET [name] = 'Zuid-Korea' WHERE name = 'South Korea'
UPDATE [dbo].[Countries] SET [name] = 'Zuid Soedan' WHERE name = 'South Sudan'
UPDATE [dbo].[Countries] SET [name] = 'Spanje' WHERE name = 'Spain'
UPDATE [dbo].[Countries] SET [name] = 'Sri Lanka' WHERE name = 'Sri Lanka'
UPDATE [dbo].[Countries] SET [name] = 'St. Vincent Grenadines' WHERE name = 'St. Vincent Grenadines'
UPDATE [dbo].[Countries] SET [name] = 'Soedan' WHERE name = 'Sudan'
UPDATE [dbo].[Countries] SET [name] = 'Suriname' WHERE name = 'Suriname'
UPDATE [dbo].[Countries] SET [name] = 'Svalbard en Jan Mayen' WHERE name = 'Svalbard and Jan Mayen'
UPDATE [dbo].[Countries] SET [name] = 'Zweden' WHERE name = 'Sweden'
UPDATE [dbo].[Countries] SET [name] = 'Zwitserland' WHERE name = 'Switzerland'
UPDATE [dbo].[Countries] SET [name] = 'Syrië' WHERE name = 'Syria'
UPDATE [dbo].[Countries] SET [name] = 'Taiwan' WHERE name = 'Taiwan'
UPDATE [dbo].[Countries] SET [name] = 'Tadzjikistan' WHERE name = 'Tajikistan'
UPDATE [dbo].[Countries] SET [name] = 'Tanzania' WHERE name = 'Tanzania'
UPDATE [dbo].[Countries] SET [name] = 'Thailand' WHERE name = 'Thailand'
UPDATE [dbo].[Countries] SET [name] = 'Oost-Timor' WHERE name = 'Timor-Leste'
UPDATE [dbo].[Countries] SET [name] = 'Gaan' WHERE name = 'Togo'
UPDATE [dbo].[Countries] SET [name] = 'Tokelau' WHERE name = 'Tokelau'
UPDATE [dbo].[Countries] SET [name] = 'Tonga' WHERE name = 'Tonga'
UPDATE [dbo].[Countries] SET [name] = 'Trinidad en Tobago' WHERE name = 'Trinidad and Tobago'
UPDATE [dbo].[Countries] SET [name] = 'Tunesië' WHERE name = 'Tunisia'
UPDATE [dbo].[Countries] SET [name] = 'kalkoen' WHERE name = 'Turkey'
UPDATE [dbo].[Countries] SET [name] = 'Turkmenistan' WHERE name = 'Turkmenistan'
UPDATE [dbo].[Countries] SET [name] = 'Turks-en Caicoseilanden' WHERE name = 'Turks and Caicos'
UPDATE [dbo].[Countries] SET [name] = 'Tuvalu' WHERE name = 'Tuvalu'
UPDATE [dbo].[Countries] SET [name] = 'Amerikaanse Maagdeneilanden' WHERE name = 'U.S. Virgin Islands'
UPDATE [dbo].[Countries] SET [name] = 'VAE' WHERE name = 'UAE'
UPDATE [dbo].[Countries] SET [name] = 'Oeganda' WHERE name = 'Uganda'
UPDATE [dbo].[Countries] SET [name] = 'UK' WHERE name = 'UK'
UPDATE [dbo].[Countries] SET [name] = 'Oekraïne' WHERE name = 'Ukraine'
UPDATE [dbo].[Countries] SET [name] = 'Kleine afgelegen eilanden van de Verenigde Staten' WHERE name = 'United States Minor Outlying Islands'
UPDATE [dbo].[Countries] SET [name] = 'Uruguay' WHERE name = 'Uruguay'
UPDATE [dbo].[Countries] SET [name] = 'Verenigde Staten van Amerika' WHERE name = 'USA'
UPDATE [dbo].[Countries] SET [name] = 'Oezbekistan' WHERE name = 'Uzbekistan'
UPDATE [dbo].[Countries] SET [name] = 'Vanuatu' WHERE name = 'Vanuatu'
UPDATE [dbo].[Countries] SET [name] = 'Vaticaanstad' WHERE name = 'Vatican City'
UPDATE [dbo].[Countries] SET [name] = 'Venezuela' WHERE name = 'Venezuela'
UPDATE [dbo].[Countries] SET [name] = 'Vietnam' WHERE name = 'Vietnam'
UPDATE [dbo].[Countries] SET [name] = 'Wallis en Futuna' WHERE name = 'Wallis and Futuna'
UPDATE [dbo].[Countries] SET [name] = 'Westelijke Sahara' WHERE name = 'Western Sahara'
UPDATE [dbo].[Countries] SET [name] = 'Jemen' WHERE name = 'Yemen'
UPDATE [dbo].[Countries] SET [name] = 'Zambia' WHERE name = 'Zambia'
UPDATE [dbo].[Countries] SET [name] = 'Zimbabwe' WHERE name = 'Zimbabwe'
