//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesNL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesNL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoronaMap.Properties.ResourcesNL", typeof(ResourcesNL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF.
        /// </summary>
        public static string Afghanistan {
            get {
                return ResourceManager.GetString("Afghanistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AX.
        /// </summary>
        public static string Aland_eilanden {
            get {
                return ResourceManager.GetString("Aland-eilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL.
        /// </summary>
        public static string Albanië {
            get {
                return ResourceManager.GetString("Albanië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DZ.
        /// </summary>
        public static string Algerije {
            get {
                return ResourceManager.GetString("Algerije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS.
        /// </summary>
        public static string Amerikaans_Samoa {
            get {
                return ResourceManager.GetString("Amerikaans Samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VI.
        /// </summary>
        public static string Amerikaanse_Maagdeneilanden {
            get {
                return ResourceManager.GetString("Amerikaanse Maagdeneilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        public static string Andorra {
            get {
                return ResourceManager.GetString("Andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AO.
        /// </summary>
        public static string Angola {
            get {
                return ResourceManager.GetString("Angola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        public static string Anguilla {
            get {
                return ResourceManager.GetString("Anguilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AQ.
        /// </summary>
        public static string Antarctica {
            get {
                return ResourceManager.GetString("Antarctica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        public static string Antigua_en_Barbuda {
            get {
                return ResourceManager.GetString("Antigua en Barbuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR.
        /// </summary>
        public static string Argentinië {
            get {
                return ResourceManager.GetString("Argentinië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string Armenië {
            get {
                return ResourceManager.GetString("Armenië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AW.
        /// </summary>
        public static string Aruba {
            get {
                return ResourceManager.GetString("Aruba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU.
        /// </summary>
        public static string Australië {
            get {
                return ResourceManager.GetString("Australië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZ.
        /// </summary>
        public static string Azerbeidzjan {
            get {
                return ResourceManager.GetString("Azerbeidzjan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS.
        /// </summary>
        public static string Bahamas {
            get {
                return ResourceManager.GetString("Bahamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH.
        /// </summary>
        public static string Bahrein {
            get {
                return ResourceManager.GetString("Bahrein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD.
        /// </summary>
        public static string Bangladesh {
            get {
                return ResourceManager.GetString("Bangladesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB.
        /// </summary>
        public static string Barbados {
            get {
                return ResourceManager.GetString("Barbados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        public static string België {
            get {
                return ResourceManager.GetString("België", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BZ.
        /// </summary>
        public static string Belize {
            get {
                return ResourceManager.GetString("Belize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BJ.
        /// </summary>
        public static string Benin {
            get {
                return ResourceManager.GetString("Benin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM.
        /// </summary>
        public static string Bermuda {
            get {
                return ResourceManager.GetString("Bermuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT.
        /// </summary>
        public static string Bhutan {
            get {
                return ResourceManager.GetString("Bhutan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO.
        /// </summary>
        public static string Bolivia {
            get {
                return ResourceManager.GetString("Bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BQ.
        /// </summary>
        public static string Bonaire__Sint_Eustatius_en_Saba {
            get {
                return ResourceManager.GetString("Bonaire, Sint Eustatius en Saba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA.
        /// </summary>
        public static string Bosnië_Herzegovina {
            get {
                return ResourceManager.GetString("Bosnië-Herzegovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BW.
        /// </summary>
        public static string Botswana {
            get {
                return ResourceManager.GetString("Botswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BV.
        /// </summary>
        public static string Bouvet_Island {
            get {
                return ResourceManager.GetString("Bouvet Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BR.
        /// </summary>
        public static string Brazilië {
            get {
                return ResourceManager.GetString("Brazilië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO.
        /// </summary>
        public static string Brits_Indisch_oceaan_gebied {
            get {
                return ResourceManager.GetString("Brits-Indisch oceaan gebied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VG.
        /// </summary>
        public static string Britse_Maagdeneilanden {
            get {
                return ResourceManager.GetString("Britse Maagdeneilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN.
        /// </summary>
        public static string Brunei {
            get {
                return ResourceManager.GetString("Brunei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG.
        /// </summary>
        public static string Bulgarije {
            get {
                return ResourceManager.GetString("Bulgarije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BF.
        /// </summary>
        public static string Burkina_Faso {
            get {
                return ResourceManager.GetString("Burkina Faso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BI.
        /// </summary>
        public static string Burundi {
            get {
                return ResourceManager.GetString("Burundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        public static string Cabo_Verde {
            get {
                return ResourceManager.GetString("Cabo Verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KH.
        /// </summary>
        public static string Cambodja {
            get {
                return ResourceManager.GetString("Cambodja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        public static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF.
        /// </summary>
        public static string Centraal_Afrikaanse_Republiek {
            get {
                return ResourceManager.GetString("Centraal-Afrikaanse Republiek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL.
        /// </summary>
        public static string Chili {
            get {
                return ResourceManager.GetString("Chili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string Cocos__Keeling__eilanden {
            get {
                return ResourceManager.GetString("Cocos (Keeling) eilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO.
        /// </summary>
        public static string Colombia {
            get {
                return ResourceManager.GetString("Colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        public static string Comoren {
            get {
                return ResourceManager.GetString("Comoren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CG.
        /// </summary>
        public static string Congo {
            get {
                return ResourceManager.GetString("Congo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK.
        /// </summary>
        public static string Cookeilanden {
            get {
                return ResourceManager.GetString("Cookeilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string Costa_Rica {
            get {
                return ResourceManager.GetString("Costa Rica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CU.
        /// </summary>
        public static string Cuba {
            get {
                return ResourceManager.GetString("Cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CW.
        /// </summary>
        public static string Curacao {
            get {
                return ResourceManager.GetString("Curacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CW.
        /// </summary>
        public static string Curaçao {
            get {
                return ResourceManager.GetString("Curaçao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CY.
        /// </summary>
        public static string Cyprus {
            get {
                return ResourceManager.GetString("Cyprus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK.
        /// </summary>
        public static string Denemarken {
            get {
                return ResourceManager.GetString("Denemarken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJ.
        /// </summary>
        public static string Djibouti {
            get {
                return ResourceManager.GetString("Djibouti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM.
        /// </summary>
        public static string Dominica {
            get {
                return ResourceManager.GetString("Dominica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO.
        /// </summary>
        public static string Dominicaanse_Republiek {
            get {
                return ResourceManager.GetString("Dominicaanse Republiek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD.
        /// </summary>
        public static string DRC {
            get {
                return ResourceManager.GetString("DRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        public static string Duitsland {
            get {
                return ResourceManager.GetString("Duitsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC.
        /// </summary>
        public static string Ecuador {
            get {
                return ResourceManager.GetString("Ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EG.
        /// </summary>
        public static string Egypte {
            get {
                return ResourceManager.GetString("Egypte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SV.
        /// </summary>
        public static string El_Salvador {
            get {
                return ResourceManager.GetString("El Salvador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GQ.
        /// </summary>
        public static string Equatoriaal_Guinea {
            get {
                return ResourceManager.GetString("Equatoriaal-Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER.
        /// </summary>
        public static string Eritrea {
            get {
                return ResourceManager.GetString("Eritrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EE.
        /// </summary>
        public static string Estland {
            get {
                return ResourceManager.GetString("Estland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZ.
        /// </summary>
        public static string Eswatini {
            get {
                return ResourceManager.GetString("Eswatini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ET.
        /// </summary>
        public static string Ethiopië {
            get {
                return ResourceManager.GetString("Ethiopië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FO.
        /// </summary>
        public static string Faeröer {
            get {
                return ResourceManager.GetString("Faeröer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK.
        /// </summary>
        public static string Falkland_Eilanden {
            get {
                return ResourceManager.GetString("Falkland Eilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FJ.
        /// </summary>
        public static string Fiji {
            get {
                return ResourceManager.GetString("Fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH.
        /// </summary>
        public static string Filippijnen {
            get {
                return ResourceManager.GetString("Filippijnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI.
        /// </summary>
        public static string Finland {
            get {
                return ResourceManager.GetString("Finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        public static string Frankrijk {
            get {
                return ResourceManager.GetString("Frankrijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GF.
        /// </summary>
        public static string Frans_Guyana {
            get {
                return ResourceManager.GetString("Frans-Guyana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PF.
        /// </summary>
        public static string Frans_Polynesië {
            get {
                return ResourceManager.GetString("Frans-Polynesië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF.
        /// </summary>
        public static string Franse_zuidelijke_gebieden {
            get {
                return ResourceManager.GetString("Franse zuidelijke gebieden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GA.
        /// </summary>
        public static string Gabon {
            get {
                return ResourceManager.GetString("Gabon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM.
        /// </summary>
        public static string Gambia {
            get {
                return ResourceManager.GetString("Gambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE.
        /// </summary>
        public static string Georgië {
            get {
                return ResourceManager.GetString("Georgië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GH.
        /// </summary>
        public static string Ghana {
            get {
                return ResourceManager.GetString("Ghana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI.
        /// </summary>
        public static string Gibraltar {
            get {
                return ResourceManager.GetString("Gibraltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GD.
        /// </summary>
        public static string Grenada {
            get {
                return ResourceManager.GetString("Grenada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR.
        /// </summary>
        public static string Griekenland {
            get {
                return ResourceManager.GetString("Griekenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL.
        /// </summary>
        public static string Groenland {
            get {
                return ResourceManager.GetString("Groenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP.
        /// </summary>
        public static string Guadeloupe {
            get {
                return ResourceManager.GetString("Guadeloupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GU.
        /// </summary>
        public static string Guam {
            get {
                return ResourceManager.GetString("Guam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GT.
        /// </summary>
        public static string Guatemala {
            get {
                return ResourceManager.GetString("Guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GG.
        /// </summary>
        public static string Guernsey {
            get {
                return ResourceManager.GetString("Guernsey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GN.
        /// </summary>
        public static string Guinea {
            get {
                return ResourceManager.GetString("Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GW.
        /// </summary>
        public static string Guinee_Bissau {
            get {
                return ResourceManager.GetString("Guinee-Bissau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GY.
        /// </summary>
        public static string Guyana {
            get {
                return ResourceManager.GetString("Guyana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT.
        /// </summary>
        public static string Haïti {
            get {
                return ResourceManager.GetString("Haïti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HM.
        /// </summary>
        public static string Heard_Island_en_Mcdonald_Islands {
            get {
                return ResourceManager.GetString("Heard Island en Mcdonald Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN.
        /// </summary>
        public static string Honduras {
            get {
                return ResourceManager.GetString("Honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HK.
        /// </summary>
        public static string Hong_Kong {
            get {
                return ResourceManager.GetString("Hong Kong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HU.
        /// </summary>
        public static string Hongarije {
            get {
                return ResourceManager.GetString("Hongarije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE.
        /// </summary>
        public static string Ierland {
            get {
                return ResourceManager.GetString("Ierland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        public static string IJsland {
            get {
                return ResourceManager.GetString("IJsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        public static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Indonesië {
            get {
                return ResourceManager.GetString("Indonesië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ.
        /// </summary>
        public static string Irak {
            get {
                return ResourceManager.GetString("Irak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR.
        /// </summary>
        public static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM.
        /// </summary>
        public static string Isle_of_Man {
            get {
                return ResourceManager.GetString("Isle of Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL.
        /// </summary>
        public static string Israël {
            get {
                return ResourceManager.GetString("Israël", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string Italië {
            get {
                return ResourceManager.GetString("Italië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI.
        /// </summary>
        public static string Ivoorkust {
            get {
                return ResourceManager.GetString("Ivoorkust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JM.
        /// </summary>
        public static string Jamaica {
            get {
                return ResourceManager.GetString("Jamaica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YE.
        /// </summary>
        public static string Jemen {
            get {
                return ResourceManager.GetString("Jemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JE.
        /// </summary>
        public static string Jersey {
            get {
                return ResourceManager.GetString("Jersey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JO.
        /// </summary>
        public static string Jordanië {
            get {
                return ResourceManager.GetString("Jordanië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KY.
        /// </summary>
        public static string Kaaiman_Eilanden {
            get {
                return ResourceManager.GetString("Kaaiman Eilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM.
        /// </summary>
        public static string Kameroen {
            get {
                return ResourceManager.GetString("Kameroen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Kanaal_eilanden {
            get {
                return ResourceManager.GetString("Kanaal eilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KZ.
        /// </summary>
        public static string Kazachstan {
            get {
                return ResourceManager.GetString("Kazachstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KE.
        /// </summary>
        public static string Kenia {
            get {
                return ResourceManager.GetString("Kenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CX.
        /// </summary>
        public static string Kersteiland {
            get {
                return ResourceManager.GetString("Kersteiland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KG.
        /// </summary>
        public static string Kirgizië {
            get {
                return ResourceManager.GetString("Kirgizië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KI.
        /// </summary>
        public static string Kiribati {
            get {
                return ResourceManager.GetString("Kiribati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UM.
        /// </summary>
        public static string Kleine_afgelegen_eilanden_van_de_Verenigde_Staten {
            get {
                return ResourceManager.GetString("Kleine afgelegen eilanden van de Verenigde Staten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KW.
        /// </summary>
        public static string Koeweit {
            get {
                return ResourceManager.GetString("Koeweit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XK.
        /// </summary>
        public static string Kosovo____betwist_gebied_ {
            get {
                return ResourceManager.GetString("Kosovo * (betwist gebied)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string Kroatië {
            get {
                return ResourceManager.GetString("Kroatië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA.
        /// </summary>
        public static string Laos {
            get {
                return ResourceManager.GetString("Laos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS.
        /// </summary>
        public static string Lesotho {
            get {
                return ResourceManager.GetString("Lesotho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LV.
        /// </summary>
        public static string Letland {
            get {
                return ResourceManager.GetString("Letland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LB.
        /// </summary>
        public static string Libanon {
            get {
                return ResourceManager.GetString("Libanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR.
        /// </summary>
        public static string Liberia {
            get {
                return ResourceManager.GetString("Liberia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LY.
        /// </summary>
        public static string Libië {
            get {
                return ResourceManager.GetString("Libië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LI.
        /// </summary>
        public static string Liechtenstein {
            get {
                return ResourceManager.GetString("Liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LT.
        /// </summary>
        public static string Litouwen {
            get {
                return ResourceManager.GetString("Litouwen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LU.
        /// </summary>
        public static string Luxemburg {
            get {
                return ResourceManager.GetString("Luxemburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MO.
        /// </summary>
        public static string Macao {
            get {
                return ResourceManager.GetString("Macao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG.
        /// </summary>
        public static string Madagascar {
            get {
                return ResourceManager.GetString("Madagascar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW.
        /// </summary>
        public static string Malawi {
            get {
                return ResourceManager.GetString("Malawi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MV.
        /// </summary>
        public static string Maldiven {
            get {
                return ResourceManager.GetString("Maldiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY.
        /// </summary>
        public static string Maleisië {
            get {
                return ResourceManager.GetString("Maleisië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ML.
        /// </summary>
        public static string Mali {
            get {
                return ResourceManager.GetString("Mali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        public static string Malta {
            get {
                return ResourceManager.GetString("Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MH.
        /// </summary>
        public static string Marshall_eilanden {
            get {
                return ResourceManager.GetString("Marshall eilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ.
        /// </summary>
        public static string Martinique {
            get {
                return ResourceManager.GetString("Martinique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR.
        /// </summary>
        public static string Mauritanië {
            get {
                return ResourceManager.GetString("Mauritanië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU.
        /// </summary>
        public static string Mauritius {
            get {
                return ResourceManager.GetString("Mauritius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YT.
        /// </summary>
        public static string Mayotte {
            get {
                return ResourceManager.GetString("Mayotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX.
        /// </summary>
        public static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM.
        /// </summary>
        public static string Micronesië {
            get {
                return ResourceManager.GetString("Micronesië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        public static string Moldavië {
            get {
                return ResourceManager.GetString("Moldavië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        public static string Monaco {
            get {
                return ResourceManager.GetString("Monaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MN.
        /// </summary>
        public static string Mongolië {
            get {
                return ResourceManager.GetString("Mongolië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ME.
        /// </summary>
        public static string Montenegro {
            get {
                return ResourceManager.GetString("Montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        public static string Montserrat {
            get {
                return ResourceManager.GetString("Montserrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA.
        /// </summary>
        public static string Morocco {
            get {
                return ResourceManager.GetString("Morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZ.
        /// </summary>
        public static string Mozambique {
            get {
                return ResourceManager.GetString("Mozambique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        public static string Myanmar {
            get {
                return ResourceManager.GetString("Myanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Namibië {
            get {
                return ResourceManager.GetString("Namibië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR.
        /// </summary>
        public static string Nauru {
            get {
                return ResourceManager.GetString("Nauru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        public static string Nederland {
            get {
                return ResourceManager.GetString("Nederland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NP.
        /// </summary>
        public static string Nepal {
            get {
                return ResourceManager.GetString("Nepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NI.
        /// </summary>
        public static string Nicaragua {
            get {
                return ResourceManager.GetString("Nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC.
        /// </summary>
        public static string Nieuw_Caledonië {
            get {
                return ResourceManager.GetString("Nieuw-Caledonië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZ.
        /// </summary>
        public static string Nieuw_Zeeland {
            get {
                return ResourceManager.GetString("Nieuw-Zeeland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string Niger {
            get {
                return ResourceManager.GetString("Niger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        public static string Nigeria {
            get {
                return ResourceManager.GetString("Nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NU.
        /// </summary>
        public static string Niue {
            get {
                return ResourceManager.GetString("Niue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KP.
        /// </summary>
        public static string Noord_Korea {
            get {
                return ResourceManager.GetString("Noord Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MK.
        /// </summary>
        public static string Noord_Macedonië {
            get {
                return ResourceManager.GetString("Noord-Macedonië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        public static string noordelijke_Mariana_eilanden {
            get {
                return ResourceManager.GetString("noordelijke Mariana eilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string Noorwegen {
            get {
                return ResourceManager.GetString("Noorwegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NF.
        /// </summary>
        public static string Norfolkeiland {
            get {
                return ResourceManager.GetString("Norfolkeiland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UG.
        /// </summary>
        public static string Oeganda {
            get {
                return ResourceManager.GetString("Oeganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA.
        /// </summary>
        public static string Oekraïne {
            get {
                return ResourceManager.GetString("Oekraïne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UZ.
        /// </summary>
        public static string Oezbekistan {
            get {
                return ResourceManager.GetString("Oezbekistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OM.
        /// </summary>
        public static string Oman {
            get {
                return ResourceManager.GetString("Oman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL.
        /// </summary>
        public static string Oost_Timor {
            get {
                return ResourceManager.GetString("Oost-Timor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT.
        /// </summary>
        public static string Oostenrijk {
            get {
                return ResourceManager.GetString("Oostenrijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK.
        /// </summary>
        public static string Pakistan {
            get {
                return ResourceManager.GetString("Pakistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PW.
        /// </summary>
        public static string Palau {
            get {
                return ResourceManager.GetString("Palau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS.
        /// </summary>
        public static string Palestina {
            get {
                return ResourceManager.GetString("Palestina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA.
        /// </summary>
        public static string Panama {
            get {
                return ResourceManager.GetString("Panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PG.
        /// </summary>
        public static string Papoea_Nieuw_Guinea {
            get {
                return ResourceManager.GetString("Papoea-Nieuw-Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PY.
        /// </summary>
        public static string Paraguay {
            get {
                return ResourceManager.GetString("Paraguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE.
        /// </summary>
        public static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PN.
        /// </summary>
        public static string Pitcairn {
            get {
                return ResourceManager.GetString("Pitcairn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        public static string Polen {
            get {
                return ResourceManager.GetString("Polen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        public static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR.
        /// </summary>
        public static string Puerto_Rico {
            get {
                return ResourceManager.GetString("Puerto Rico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        public static string Qatar {
            get {
                return ResourceManager.GetString("Qatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE.
        /// </summary>
        public static string Réunion {
            get {
                return ResourceManager.GetString("Réunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO.
        /// </summary>
        public static string Roemenië {
            get {
                return ResourceManager.GetString("Roemenië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RU.
        /// </summary>
        public static string Rusland {
            get {
                return ResourceManager.GetString("Rusland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RW.
        /// </summary>
        public static string Rwanda {
            get {
                return ResourceManager.GetString("Rwanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KN.
        /// </summary>
        public static string Saint_Kitts_en_Nevis {
            get {
                return ResourceManager.GetString("Saint Kitts en Nevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string Saint_Lucia {
            get {
                return ResourceManager.GetString("Saint Lucia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string Saint_Pierre_en_Miquelon {
            get {
                return ResourceManager.GetString("Saint Pierre en Miquelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS.
        /// </summary>
        public static string Samoa {
            get {
                return ResourceManager.GetString("Samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SM.
        /// </summary>
        public static string San_Marino {
            get {
                return ResourceManager.GetString("San Marino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST.
        /// </summary>
        public static string Sao_Tome_en_Principe {
            get {
                return ResourceManager.GetString("Sao Tome en Principe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string Saoedi_Arabië {
            get {
                return ResourceManager.GetString("Saoedi-Arabië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        public static string Senegal {
            get {
                return ResourceManager.GetString("Senegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS.
        /// </summary>
        public static string Servië {
            get {
                return ResourceManager.GetString("Servië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.
        /// </summary>
        public static string Seychellen {
            get {
                return ResourceManager.GetString("Seychellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL.
        /// </summary>
        public static string Sierra_Leone {
            get {
                return ResourceManager.GetString("Sierra Leone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG.
        /// </summary>
        public static string Singapore {
            get {
                return ResourceManager.GetString("Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL.
        /// </summary>
        public static string Sint_Bartholomeus {
            get {
                return ResourceManager.GetString("Sint-Bartholomeus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH.
        /// </summary>
        public static string Sint_Helena__Ascension_en_Tristan_da_Cunha {
            get {
                return ResourceManager.GetString("Sint-Helena, Ascension en Tristan da Cunha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string Slovenië {
            get {
                return ResourceManager.GetString("Slovenië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SK.
        /// </summary>
        public static string Slowakije {
            get {
                return ResourceManager.GetString("Slowakije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        public static string Soedan {
            get {
                return ResourceManager.GetString("Soedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SB.
        /// </summary>
        public static string Solomon_eilanden {
            get {
                return ResourceManager.GetString("Solomon eilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO.
        /// </summary>
        public static string Somalië {
            get {
                return ResourceManager.GetString("Somalië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KR.
        /// </summary>
        public static string South_Korea {
            get {
                return ResourceManager.GetString("South Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES.
        /// </summary>
        public static string Spanje {
            get {
                return ResourceManager.GetString("Spanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LK.
        /// </summary>
        public static string Sri_Lanka {
            get {
                return ResourceManager.GetString("Sri Lanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC.
        /// </summary>
        public static string St__Vincent_Grenadines {
            get {
                return ResourceManager.GetString("St. Vincent Grenadines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        public static string Suriname {
            get {
                return ResourceManager.GetString("Suriname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SJ.
        /// </summary>
        public static string Svalbard_en_Jan_Mayen {
            get {
                return ResourceManager.GetString("Svalbard en Jan Mayen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SY.
        /// </summary>
        public static string Syrië {
            get {
                return ResourceManager.GetString("Syrië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TJ.
        /// </summary>
        public static string Tadzjikistan {
            get {
                return ResourceManager.GetString("Tadzjikistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TW.
        /// </summary>
        public static string Taiwan {
            get {
                return ResourceManager.GetString("Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TZ.
        /// </summary>
        public static string Tanzania {
            get {
                return ResourceManager.GetString("Tanzania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TH.
        /// </summary>
        public static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TG.
        /// </summary>
        public static string Togo {
            get {
                return ResourceManager.GetString("Togo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TK.
        /// </summary>
        public static string Tokelau {
            get {
                return ResourceManager.GetString("Tokelau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        public static string Tonga {
            get {
                return ResourceManager.GetString("Tonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT.
        /// </summary>
        public static string Trinidad_en_Tobago {
            get {
                return ResourceManager.GetString("Trinidad en Tobago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        public static string Tsjaad {
            get {
                return ResourceManager.GetString("Tsjaad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZ.
        /// </summary>
        public static string Tsjechië {
            get {
                return ResourceManager.GetString("Tsjechië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TN.
        /// </summary>
        public static string Tunesië {
            get {
                return ResourceManager.GetString("Tunesië", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        public static string Turkije {
            get {
                return ResourceManager.GetString("Turkije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TM.
        /// </summary>
        public static string Turkmenistan {
            get {
                return ResourceManager.GetString("Turkmenistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC.
        /// </summary>
        public static string Turks_en_Caicoseilanden {
            get {
                return ResourceManager.GetString("Turks-en Caicoseilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string Tuvalu {
            get {
                return ResourceManager.GetString("Tuvalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UY.
        /// </summary>
        public static string Uruguay {
            get {
                return ResourceManager.GetString("Uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE.
        /// </summary>
        public static string VAE {
            get {
                return ResourceManager.GetString("VAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VU.
        /// </summary>
        public static string Vanuatu {
            get {
                return ResourceManager.GetString("Vanuatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA.
        /// </summary>
        public static string Vaticaanstad {
            get {
                return ResourceManager.GetString("Vaticaanstad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VE.
        /// </summary>
        public static string Venezuela {
            get {
                return ResourceManager.GetString("Venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string Verenigd_Koningkrijk {
            get {
                return ResourceManager.GetString("Verenigd Koningkrijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        public static string Verenigde_Staten_van_Amerika {
            get {
                return ResourceManager.GetString("Verenigde Staten van Amerika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VN.
        /// </summary>
        public static string Vietnam {
            get {
                return ResourceManager.GetString("Vietnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WF.
        /// </summary>
        public static string Wallis_en_Futuna {
            get {
                return ResourceManager.GetString("Wallis en Futuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EH.
        /// </summary>
        public static string Westelijke_Sahara {
            get {
                return ResourceManager.GetString("Westelijke Sahara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY.
        /// </summary>
        public static string Wit_Rusland {
            get {
                return ResourceManager.GetString("Wit-Rusland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZM.
        /// </summary>
        public static string Zambia {
            get {
                return ResourceManager.GetString("Zambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZW.
        /// </summary>
        public static string Zimbabwe {
            get {
                return ResourceManager.GetString("Zimbabwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZA.
        /// </summary>
        public static string Zuid_Afrika {
            get {
                return ResourceManager.GetString("Zuid-Afrika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS.
        /// </summary>
        public static string Zuid_Georgië_en_de_Zuidelijke_Sandwicheilanden {
            get {
                return ResourceManager.GetString("Zuid-Georgië en de Zuidelijke Sandwicheilanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KR.
        /// </summary>
        public static string Zuid_Korea {
            get {
                return ResourceManager.GetString("Zuid-Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS.
        /// </summary>
        public static string Zuid_Soedan {
            get {
                return ResourceManager.GetString("Zuid Soedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string Zweden {
            get {
                return ResourceManager.GetString("Zweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH.
        /// </summary>
        public static string Zwitserland {
            get {
                return ResourceManager.GetString("Zwitserland", resourceCulture);
            }
        }
    }
}
